{"level": "WARNING", "message": "warning message", "timestamp": "2025-03-13T19:58:01.356786+00:00", "logger": "main", "module": "main", "function": "main", "line": 23, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message: division by zero\nTraceback (most recent call last):\n  File \"C:\\Users\\gilia\\Development\\projects\\algorithms\\python-logging\\main.py\", line 27, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2025-03-13T19:58:01.354777+00:00", "logger": "main", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2025-03-13T19:58:01.356786+00:00", "logger": "main", "module": "main", "function": "main", "line": 24, "thread_name": "MainThread"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2025-03-13T20:00:44.565277+00:00", "logger": "main", "module": "main", "function": "main", "line": 25, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2025-03-13T20:00:44.565277+00:00", "logger": "main", "module": "main", "function": "main", "line": 26, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2025-03-13T20:00:44.565277+00:00", "logger": "main", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2025-03-13T20:00:44.565277+00:00", "logger": "main", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2025-03-13T20:00:44.565277+00:00", "logger": "main", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message: division by zero\nTraceback (most recent call last):\n  File \"C:\\Users\\gilia\\Development\\projects\\algorithms\\python-logging\\main.py\", line 31, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2025-03-13T20:00:44.565277+00:00", "logger": "main", "module": "main", "function": "main", "line": 33, "thread_name": "MainThread"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 25, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 26, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message: division by zero\nTraceback (most recent call last):\n  File \"C:\\Users\\gilia\\Development\\projects\\algorithms\\python-logging\\main.py\", line 31, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 33, "thread_name": "MainThread"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 25, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 26, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message: division by zero\nTraceback (most recent call last):\n  File \"C:\\Users\\gilia\\Development\\projects\\algorithms\\python-logging\\main.py\", line 31, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 33, "thread_name": "MainThread"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 25, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 26, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message: division by zero\nTraceback (most recent call last):\n  File \"C:\\Users\\gilia\\Development\\projects\\algorithms\\python-logging\\main.py\", line 31, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 33, "thread_name": "MainThread"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 25, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 26, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message: division by zero\nTraceback (most recent call last):\n  File \"C:\\Users\\gilia\\Development\\projects\\algorithms\\python-logging\\main.py\", line 31, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 33, "thread_name": "MainThread"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 25, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 26, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message: division by zero\nTraceback (most recent call last):\n  File \"C:\\Users\\gilia\\Development\\projects\\algorithms\\python-logging\\main.py\", line 31, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2025-03-13T20:00:44.573724+00:00", "logger": "main", "module": "main", "function": "main", "line": 33, "thread_name": "MainThread"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2025-03-13T20:00:44.580448+00:00", "logger": "main", "module": "main", "function": "main", "line": 25, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2025-03-13T20:00:44.580448+00:00", "logger": "main", "module": "main", "function": "main", "line": 26, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2025-03-13T20:00:44.580448+00:00", "logger": "main", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread"}
